@ECHO OFF

TITLE MAIN BATCH FILE

SET MAIN_PATH=%~dp0
SET PRE_PATH=%MAIN_PATH%PREREQUISITES


REM ADDING NIA USER
SET NEW_USER=%PRE_PATH%\NEW_USER.bat
call "%NEW_USER%"


REM CONFIGURING MOBILE 2 ADAPTER TO DHCP
SET MOBILE_2_CONFIG=%PRE_PATH%\MOBILE_NET_CONFIG.bat
call "%MOBILE_2_CONFIG%"

REM RENAMING USB DRIVE
SET USB_RENAME=%PRE_PATH%\RENAME_USB_DRIVE.bat
call "%USB_RENAME%"


REM INSTALLING PREREQUISITES

REM INSTALLING CODEMETER
SET CODEMETER_PATH=%MAIN_PATH%1_CodeMeter\INSTALL.bat
call "%CODEMETER_PATH%"

REM ZEBRA BARCODE DRIVER 
SET ZEBRA_PATH=%MAIN_PATH%2_Dermalog_SW_Preq\1_Enrollment\01_Barcode-Scanner\INSTALL.bat
call "%ZEBRA_PATH%"

REM install FINGERPRINT driver 
SET FINGERPRINT_PATH = %MAIN_PATH%2_Dermalog SW preq/1_Enrollment/02_Fingerprint-Scanner/INSTALL.bat
call "%FINGERPRINT_PATH%"

REM install SMART CARD driver 
SET SMART_CARD_PATH = %MAIN_PATH%2_Dermalog SW preq/1_Enrollment/03_Smart-Card-Reader/INSTALL.bat
call "%SMART_CARD_PATH%"

REM install 04_Iris-Scanner driver 
SET IRIS_SCANNER_PATH = %MAIN_PATH%2_Dermalog SW preq/1_Enrollment/04_Iris-Scanner/INSTALL.bat
call "%IRIS_SCANNER_PATH%"

REM install Signature-Pad driver 
SET SIGNATURE_PAD_PATH = %MAIN_PATH%2_Dermalog SW preq/1_Enrollment/05_Signature-Pad/INSTALL.bat
call "%SIGNATURE_PAD_PATH%"

REM install Receipt-Printer
SET RECEIPT_PRINTER_PATH = %MAIN_PATH%2_Dermalog SW preq/1_Enrollment/06_Receipt-Printer/INSTALL.bat
call "%RECEIPT_PRINTER_PATH%"

REM install Java Runtime
SET JAVA_RUNTIME_PATH = %MAIN_PATH%2_Dermalog SW preq/1_Enrollment/INSTALL.bat
call "%JAVA_RUNTIME_PATH%"

PAUSE
